name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore src/CinnamonTrees.sln

      - name: Build solution
        run: dotnet build src/CinnamonTrees.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test src/CinnamonTrees.sln --no-build --configuration Release
